### ISSUE TITLE
Targeting netcoreapp3.1

### ISSUE THREAD

**Issue by govorovvs** [YohDeadfall/Yoh.Text.Json.NamingPolicies#18]
Does netcoreapp3.1 target really required for the package? Looks like netstandard2.1 will be sufficient.

**Comment by YohDeadfall** [comment]
.NET Standard doesn't include `System.Text.Json`, and therefore, cannot be used as a minimal required version. That library was started only since .NET Core 3.0, but because of it's deprecation the minimal version of .NET is Core 3.1.

**Comment by govorovvs** [comment]
System.Text.Json is a separate package, which supports even .NET Framework 4.6.1 https://www.nuget.org/packages/System.Text.Json/4.6.0#supportedframeworks-body-tab

**Comment by YohDeadfall** [comment]
Then MSDN has wrong information about the minimal required version. In that case I can target it to a lower version.

**Comment by govorovvs** [comment]
Just add PackageReference to the `System.Text.Json` and target `netstandard2.1`

**Comment by YohDeadfall** [comment]
Not so easy actually because I used range and index types, so need to adjust code a bit to be .NET Standard compatible. It will be ready today with some bug fixes.

**Comment by govorovvs** [comment]
range and index types are compatible with `netstandard2.1`

**Comment by YohDeadfall** [comment]
Yeah, but I used .NET Standard 2.0 as `System.Text.Json` since the same code is proposed to be in .NET itself (no idea when it happen) and it would be easier to maintain if that repo and a PR moving it to .NET will contain the same code.

In case you're interested in the pull request on moving it to .NET, here is it: dotnet/runtime#69613.

**Comment by YohDeadfall** [comment]
Fixed via 82974163fb3a48fcffb9ef3fc60c4a3b91549640, thank you for bringing it up! A new version will be ready as soon as I address changes requested by @NinoFloris in the .NET repo here and there.
