### ISSUE TITLE
Set repository url

### ISSUE THREAD

**Issue by thompson-tomo** [YohDeadfall/Yoh.Text.Json.NamingPolicies#89]
The nuget package should have the repository url set

**Comment by YohDeadfall** [comment]
It's set already in `Directory.Build.props` and I can see that link at [Nuget.org]:(https://www.nuget.org/packages/Yoh.Text.Json.NamingPolicies/) in the about section. Did you mean something else?

https://github.com/YohDeadfall/Yoh.Text.Json.NamingPolicies/blob/93ae69d43f8b412a2a43c3eae2099593b4a1d37e/Directory.Build.props#L10

**Comment by YohDeadfall** [comment]
Okay, I got what did you mean. There's no repository URL specified.
